### ISSUE TITLE
Large API Blueprint fails ( 200 KB )

### ISSUE THREAD

**Issue by Slevinski** [subosito/iglo#10]
Great project, but I'm having a problem as my API example document grows.  Once the Markdown file was close to 200 KB, Iglo started to create an empty document.

Here's my API Blueprint.
http://signbank.org/swserver/Example.md

I was able to track down the problem to the ParseMarkdown function in the parser.go file.  The "b" variable contained the Markdown, but the Markdown was lost after the "echo" to StdoutPipe.

I'm using Ubuntu 14.04 on an older iMac.

I was able to come up with a by-pass, but I don't think it's the right solution because it didn't work when I applied the same fix to "hiro".

My solution was to remove the statements involving "b", "echo", and "out".  Then I changed the last statement for Stdin to the following.
    cmd.Stdin = r

With this change, Iglo is working again for me.  There is probably a better fix for this, but I have no experience with golang.

**Comment by subosito** [comment]
Hi @Slevinski, tried locally, but working fine in my side. It produces below sizes:

```
-rw-r--r--  1 subosito  staff   988K Nov 24 21:55 API.json
-rw-r--r--  1 subosito  staff   250K Nov 24 22:01 output.html
```

Just pushed a changes based on your suggestion, 4426c4526de579a7be672427c949e253e5c271d3.
Hopefully that solves your problem :)

**Comment by Slevinski** [comment]
Thanks for investigating.  I was wondering if the problem was platform specific.  Your changes look good.  Thanks again.
