### ISSUE TITLE
error.

### ISSUE THREAD

**Issue by Karciukass** [subosito/iglo#13]
Hello,

Maybe you will know the answer in me question. I am trying to generate .html file and it seem that CSS disappear somehow. And it will looks like this:
![image](https://cloud.githubusercontent.com/assets/19343765/17846916/f42abdac-6853-11e6-9936-eb8d7c32c31b.png)

And Sometimes I get this:
![image](https://cloud.githubusercontent.com/assets/19343765/17846964/28d94c8a-6854-11e6-8525-387f1e879741.png)

**Comment by peterhellberg** [comment]
The reason for this is that the HTML is served over `file://` instead of `http://`

The template will load the CSS using the same protocol as the HTML is loaded over: <https://github.com/subosito/iglo/blob/master/template.go#L169-L171>

**Comment by Karciukass** [comment]
And what means this error?
[image: Įterptasis vaizdas 1]

2016-08-22 12:33 GMT+03:00 Peter Hellberg <notifications@github.com>:

**Comment by Karciukass** [comment]
And maybe you know where I can find notes about errors what means like:
[image: Įterptasis vaizdas 1]


2016-08-22 13:12 GMT+03:00 Karolis Tamasauskas <karciukass@gmail.com>:

**Comment by subosito** [comment]
Going to close this issue, since conversation is now using email instead of this issue.

> Note: Actually, email conversation is not about *real* issue, it's just a matter of personal template customisation.
